# Generated by Django 4.1.7 on 2024-07-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cord_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='カードNo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_expiry',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='有効期限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='セキュリティキー'),
        ),
    ]
